version: '3'
services:

    server:

      build:
        context: .
        dockerfile: Dockerfile.server
      image: rust_server
      ports:
        - "1331:1331"
      networks:
            - backend

    proxy:
      build:
        context: .
        dockerfile: Dockerfile.proxy
      image: rust_proxy
      ports:
        - "30001:30001"
      networks:
            - backend

networks:
    backend: {}
