FROM ubuntu:16.04

COPY . .
#RUN apt-get update && apt-get install -y build-essential
#RUN apt-get update && apt-get install -y libtbb-dev
RUN apt-get update && apt-get install curl -y
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH /root/.cargo/bin:$PATH

RUN rustc -V

RUN cargo run --bin server
