[package]
name = "web_proxy"
version = "0.1.0"
authors = ["Oleh Bodunov <oleg.bdnf@gmail.com>"]

[dependencies]
regex = "1.0.4"
time = "0.1.32"
hyper = "0.11"
tokio-core = "0.1"
futures = "0.1"
reqwest = "0.9.0"
